// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfCore.Models;

public partial class Doctor
{
    public int Doctor_id { get; set; }

    public string f_name { get; set; }

    public string L_name { get; set; }

    public string phone_num { get; set; }

    public int? salary { get; set; }

    public int? Dept_id { get; set; }

    public virtual department Dept { get; set; }

    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();
}