// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfCore.Models;

public partial class Hospital
{
    public int Hos_id { get; set; }

    public string Hos_name { get; set; }

    public string phone_num { get; set; }

    public int? zip_code { get; set; }

    public virtual ICollection<department> departments { get; set; } = new List<department>();
}