// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfCore.Models;

public partial class Hos_address
{
    public string Hos_address1 { get; set; }

    public int? Hos_id { get; set; }

    public virtual Hospital Hos { get; set; }
}