// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfCore.Models;

public partial class Patient
{
    public int patient_id { get; set; }

    public string f_name { get; set; }

    public string l_name { get; set; }

    public string phone_num { get; set; }

    public string patient_address { get; set; }

    public int? doc_id { get; set; }

    public virtual Doctor doc { get; set; }
}